### ISSUE TITLE
[🌈 Feature] 파비콘과 오픈그래프(og) 태그를 추가한다

### ISSUE THREAD

**Issue by JengYoung** [JengYoung/portfolio#39]
## 🚀 배경 및 설명

결국 누군가에게 링크를 보낼 때 알기 쉬운 내용이 나와야 접근성이 높아진다.
이를 위한 오픈그래프 태그를 추가한다.

## ✨ 기대 결과

1. 링크를 올릴  때 적절한 이미지가 나온다.
2. 각 페이지마다 다른 오픈그래프가 나와야 한다.

## ✅ 체크 리스트

- [ ] [다음](https://ogp.me/)을 참고하며, 내게 필요한 메타 정보를 확실히 인지하자.
- [ ] 각 페이지마다 다른 헤드의 메타 정보를 가져간다.
- [ ] favicon.ico를 만들어 반영한다.

## 📑 참고자료

> 예시) 피그마에 구현되어 있으니 참고 부탁드려요! (첨부)

**Comment by jinhwansuh** [comment]
캬.... 포트폴리오 사이트 꾸미는거 멋지십니다.

하나 제보하고 갈께유

![image](https://user-images.githubusercontent.com/61727311/201465755-f9581aa9-64b1-4146-ab9e-b0d75834ccd0.png)

스킬부분 아이콘 Vercel 아이콘이 제대로 나오지 않는 오류가 있어요!  + 윈도우에선 불필요한 스크롤이 보입니다!

**Comment by JengYoung** [comment]
@jinhwansuh 
아이콘의 경우 #60 에 있어요!
스크롤의 경우 따흑 맥북 느낌으로 내고 싶어서, 가로스크롤을 쓰고 싶기는 한데... 역시 웹 접근성 측면에서 별로이려나요? 😭=
